#include <iostream>
#include <list>
#include "TFile.h"
#include "TString.h"
#include "TH1D.h"
#include "TObjArray.h"
#include "TObjString.h"
#include "TLegend.h"
#include "TCanvas.h"
#include "TColor.h"

// Global script parameters
const char* gEtaPrimeToPi0RatioHistName = "EtaPrimeToPi0Ratio";
const char* gCollisionSystem = "pPb";
Double_t gPtRangeMax = 40.;

// Auxiliary functions
TString RemoveLeadingAndTrailingSpaces(TString& string)
{
    while(string.BeginsWith(" ")) string.Remove(0,1);
    while(string.EndsWith  (" ")) string.Chop();
    return string;
}

TH1D* GetEtaPrimeToPi0Ratio(const TString& filename)
{
    // Attempt to open file
    auto file = new TFile(filename.Data());
    if(!file || file->IsZombie()) {
        return nullptr;
    }
    // Find and attempt to cast the right TH1D
    std::cout << "\"" << filename << "\": ";
    auto hist = dynamic_cast<TH1D*>(file->Get(gEtaPrimeToPi0RatioHistName));
    if(!hist) {
        std::cout << "does not contain valid histogram";
    } else {
        std::cout << "successfull";
        TString generatorName = hist->GetTitle();
        generatorName.Remove(0,generatorName.Last(',')+1);
        RemoveLeadingAndTrailingSpaces(generatorName);
        generatorName.ReplaceAll(Form(" %s", gCollisionSystem), "");
        hist->SetTitle(generatorName.Data());
    }
    std::cout << std::endl;
    return hist;
}


// Main function
// Give filenames of ROOT files generated by the AnalysePythiaMB.C macro as arguments, seperated by semicolumn.
void CompareEtaPrimeToPi0SimulationRatios(const char* filenames)
{
    // Extract file names from semicolumn seperated input string
    TString filenamesTString = filenames;
    TString filename;
    Ssiz_t dummy = 0;
    // Loop over these file names and store histograms to list
    std::cout << std::endl << "Loading files:" << std::endl;
    std::list<TH1D*> listOfHistograms;
    while (filenamesTString.Tokenize(filename, dummy, ";")) {
        RemoveLeadingAndTrailingSpaces(filename);
        // Do analysis on this file
        if(!filename.IsNull()) {
            // Attempt to load histogram and add to list
            auto hist = GetEtaPrimeToPi0Ratio(filename);
            if(hist) listOfHistograms.push_back(hist);
        }
    }
    // Check if loading was successfull
    if(!listOfHistograms.size()) {
        std::cout << std::endl << "FATAL ERROR: no histograms were loaded" << std::endl;
        std::terminate();
    }
    // Create canvas and iterator and generate legend
    auto c = new TCanvas();
    auto legend = new TLegend(0.70, 0.87-0.065*listOfHistograms.size(), 0.88, 0.87);
    legend->SetTextSize(0.04);
    legend->SetFillColor(0);
    legend->SetLineColor(0);
    // Plot first histogram and beautify
    std::list<TH1D*>::iterator it {listOfHistograms.begin()};
    auto hist = dynamic_cast<TH1D*>((*it)->Clone());
    hist->SetTitle(Form("Comparison of #eta' to #pi^{0} ratio for different MC %s generators", gCollisionSystem));
    hist->GetXaxis()->SetTitle("#it{p}_{T}");
    hist->GetYaxis()->SetTitle("#it{N}_{#eta'} / #it{N}_{#pi^{0}}");
    hist->GetXaxis()->SetRangeUser(0., gPtRangeMax);
    hist->GetYaxis()->SetRangeUser(0., 1.);
    hist->Draw("e1");
    // Plot rest of the histograms
    Int_t color = 2;
    Int_t marker = 20;
    while(it != listOfHistograms.end()) {
        (*it)->SetLineColor(TColor::GetColorDark(color));
        (*it)->SetMarkerColor(TColor::GetColorDark(color));
        (*it)->SetMarkerStyle(marker);
        legend->AddEntry(*it, (*it)->GetTitle());
        (*it)->Draw("e1 same");
        ++it;
        ++color;
        ++marker;
    }
    legend->Draw();
    // Save and close canvas
    c->SaveAs(Form("MCGeneratorComparison/GeneratorComparisons_%s.pdf", gCollisionSystem));
    c->Close();
    delete hist;
}