root -b -x -q -l 'redoFinish.C("GammaConvFlow_19.root","AnalysisResults19.root")'
root -b -x -q -l 'redoFinish.C("GammaConvFlow_21.root","AnalysisResults21.root")'
root -b -x -q -l 'redoFinish.C("GammaConvFlow_23.root","AnalysisResults23.root")'
root -b -x -q -l 'Photonv2Spectra_v2.C+("AnalysisResults19.root","0","20",19,"19")'
root -b -x -q -l 'Photonv2Spectra_v2.C+("AnalysisResults21.root","20","40",21,"21")'
root -b -x -q -l 'Photonv2Spectra_v2.C+("AnalysisResults23.root","40","80",23,"23")'
